variables:
  NEXUS_URL:      "http://swarm-nexus-ingress-controller.swarm-nexus.svc.k8s.prod-dl/repository"
  NEXUS_REPO:     "swarm-apt-hosted"

stages:
  - build-deb
  - push-deb

.template_default:
  image: harbor.wildberries.ru/swarm/swarm/swarmops/docker-factory/deb-builder:feature-swarm-235-65bcf997
  before_script:
  - export STRIPPED_VERSION="${VERSION#v}"
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^feature-.*$/ || $CI_COMMIT_BRANCH =~ /^dev$/
      variables:
        VERSION: 0-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
    - if: "$CI_COMMIT_TAG =~ /^v([0-9]+)\\.([0-9]+)\\.([0-9]+)-?([a-zA-Z0-9\\.]*)\\+?([a-zA-Z0-9\\.]*)$/"
      variables:
        VERSION: $CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA
  tags:
    - swarm

build-deb:
  stage: build-deb
  extends: .template_default
  script:
    - git submodule add -f git@gitlab-internal.wildberries.ru:swarm/system/nftables/libnftnl.git
    - git submodule set-branch --branch develop libnftnl
    - git submodule update --force --recursive --init --remote
    - git submodule update --remote --merge
    - apt install -y asciidoc
    - cd libnftnl && git branch
    - ./autogen.sh
    - make
    - sudo make install
    - ./configure
    - cd ..
    - ./install.sh
    - mv ./packages/deb/hbf-nft-${STRIPPED_VERSION}-any.deb .
  artifacts:
    paths:
      - "*.deb"

push:
  stage: push-deb
  extends: .template_default
  dependencies:
    - build-deb
  script:
    - ls -lah
    - 'curl -X POST -u "$NEXUS_USER:$NEXUS_PASSWORD" -H "Content-Type: multipart/form-data; charset=utf-8" --data-binary "@hbf-nft-${STRIPPED_VERSION}-any.deb" "$NEXUS_URL/$NEXUS_REPO/"'
  variables:
    GIT_STRATEGY: none
