include:
  - project: swarm/swarmops/devops/ci/ci-templates
    ref: v1.1.0
    file: /nexus/package.yml

stages:
  - build package
  - deploy package
  - check approve

variables:
  PACKAGE_TYPE: deb

build:
  stage: build package
  extends: .template_default
  before_script:
    - export STRIPPED_VERSION="${VERSION#v}"
    - echo $STRIPPED_VERSION
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab-internal.wildberries.ru/swarm/system/nftables/libnftnl
    - cd libnftnl
    - ./autogen.sh
    - ./configure '--with-pkgdst=/opt/swarm/' '--with-build-deb'
    - make build-deb
    - apt install ./packages/deb/swarm-libnftnl-${STRIPPED_VERSION}-any.deb
    - cd ..
    - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/swarm/lib/pkgconfig/
    - ./autogen.sh
    - ./configure '--with-pkgdst=/opt/swarm/' '--with-build-deb' '--with-json'
    - make build-deb
    - mv ./packages/deb/swarm-nft-${STRIPPED_VERSION}-any.deb .
