variables:
  NEXUS_URL:      "http://swarm-nexus-ingress-controller.swarm-nexus.svc.k8s.prod-dl/repository"
  NEXUS_REPO:     "swarm-apt-hosted"

  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone

stages:
  - check approve
  - build-deb
  - push-deb

.template_default:
  image: $IMAGE
  before_script:
    - export STRIPPED_VERSION="${VERSION#v}"
    - echo $STRIPPED_VERSION
  rules:
    - if: "$CI_COMMIT_TAG =~ /^v([0-9]+)\\.([0-9]+)\\.([0-9]+)-?([a-zA-Z0-9\\.]*)\\+?([a-zA-Z0-9\\.]*)$/"
      variables:
        VERSION: $CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^(feature|fix)-[a-z]+-\d+$/
      variables:
        VERSION: 0-$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME-$CI_COMMIT_SHORT_SHA
  tags:
    - dev
    - docker
    - linux

build-deb:
  stage: build-deb
  extends: .template_default
  script:
    - apt install -y asciidoc
    - cd libnftnl
    - chmod -R 755 .
    - ./install.sh
    - apt install ./packages/deb/swarm-libnftnl-${STRIPPED_VERSION}-any.deb
    - mv ./packages/deb/swarm-libnftnl-${STRIPPED_VERSION}-any.deb ..
    - cd ..
    - ./install.sh
    - mv ./packages/deb/swarm-nft-${STRIPPED_VERSION}-any.deb .
  artifacts:
    paths:
      - "*.deb"

push:
  stage: push-deb
  extends: .template_default
  dependencies:
    - build-deb
  script:
    - ls -lah
    - |+
      for FILE in $(ls | grep .deb)
      do
        curl -f -v -i -u "${NEXUS_USER}:${NEXUS_PASSWORD}" -H "Content-Type: multipart/form-data" --data-binary "@$FILE" "${NEXUS_URL}/${NEXUS_REPO}/"
      done
  variables:
    GIT_STRATEGY: none
  rules:
    - if: "$CI_COMMIT_TAG =~ /^v([0-9]+)\\.([0-9]+)\\.([0-9]+)-?([a-zA-Z0-9\\.]*)\\+?([a-zA-Z0-9\\.]*)$/"
      variables:
        VERSION: $CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA