variables:
  NEXUS_URL:      "http://swarm-nexus-ingress-controller.swarm-nexus.svc.k8s.prod-dl/repository"
  NEXUS_REPO:     "swarm-apt-hosted"

  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone

stages:
  - build-deb
  - push-deb

.template_default:
  image: harbor.wildberries.ru/swarm/swarm/swarmops/docker-factory/deb-builder:feature-swarm-235-65bcf997
  before_script:
  - export STRIPPED_VERSION="${VERSION#v}"
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(feature|fix)-.*$/ || $CI_COMMIT_BRANCH =~ /^dev$/
      variables:
        VERSION: 0-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA

    - if: "$CI_COMMIT_TAG =~ /^v([0-9]+)\\.([0-9]+)\\.([0-9]+)-?([a-zA-Z0-9\\.]*)\\+?([a-zA-Z0-9\\.]*)$/"
      variables:
        VERSION: $CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA
  tags:
    - swarm

build-deb:
  stage: build-deb
  extends: .template_default
  script:
    - apt install -y asciidoc
    - cd libnftnl
    - chmod -R 755 .
    - ./install.sh
    - apt install ./packages/deb/swarm-libnftnl-${STRIPPED_VERSION}-any.deb
    - mv ./packages/deb/swarm-libnftnl-${STRIPPED_VERSION}-any.deb ..
    - cd ..
    - ./install.sh
    - mv ./packages/deb/swarm-nft-${STRIPPED_VERSION}-any.deb .
  artifacts:
    paths:
      - "*.deb"

push:
  stage: push-deb
  extends: .template_default
  dependencies:
    - build-deb
  script:
    - ls -lah
    - 'curl -X POST -u "$NEXUS_USER:$NEXUS_PASSWORD" -H "Content-Type: multipart/form-data; charset=utf-8" --data-binary "@swarm-libnftnl-${STRIPPED_VERSION}-any.deb" "$NEXUS_URL/$NEXUS_REPO/"'
    - 'curl -X POST -u "$NEXUS_USER:$NEXUS_PASSWORD" -H "Content-Type: multipart/form-data; charset=utf-8" --data-binary "@swarm-nft-${STRIPPED_VERSION}-any.deb" "$NEXUS_URL/$NEXUS_REPO/"'
  variables:
    GIT_STRATEGY: none
